"""baseline

Revision ID: 0ea9052fc396
Revises: 
Create Date: 2019-10-25 10:25:42.191122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea9052fc396'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sponsor', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers'))
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('download_bits', sa.Float(), nullable=True),
    sa.Column('upload_bits', sa.Float(), nullable=True),
    sa.Column('ping', sa.Float(), nullable=True),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('test_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_tests_server_id_servers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_index(op.f('ix_tests_server_id'), 'tests', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_server_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_table('servers')
    # ### end Alembic commands ###
