"""rename with bps

Revision ID: 3c3fd5465e8f
Revises: f5ab86d2a69c
Create Date: 2019-10-25 13:17:50.032148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c3fd5465e8f'
down_revision = 'f5ab86d2a69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tests', sa.Column('download_bps', sa.Float(), nullable=True))
    # op.add_column('tests', sa.Column('upload_bps', sa.Float(), nullable=True))
    # op.drop_column('tests', 'download_bits')
    # op.drop_column('tests', 'upload_bits')
    # ### end Alembic commands ###
    op.alter_column('tests', 'download_bits', new_column_name='download_bps')
    op.alter_column('tests', 'upload_bits', new_column_name='upload_bps')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tests', sa.Column('upload_bits', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # op.add_column('tests', sa.Column('download_bits', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # op.drop_column('tests', 'upload_bps')
    # op.drop_column('tests', 'download_bps')
    # ### end Alembic commands ###
    op.alter_column('tests', 'download_bps', new_column_name='download_bits')
    op.alter_column('tests', 'upload_bps', new_column_name='upload_bits')
