"""better columns

Revision ID: f5ab86d2a69c
Revises: 0ea9052fc396
Create Date: 2019-10-25 12:44:30.200691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5ab86d2a69c'
down_revision = '0ea9052fc396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('distance_km', sa.Float(), nullable=True))
    op.drop_column('servers', 'latency')
    op.add_column('tests', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tests', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('tests', sa.Column('ping_ms', sa.Float(), nullable=True))
    op.add_column('tests', sa.Column('server_latency', sa.Float(), nullable=True))
    op.drop_column('tests', 'ping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('ping', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tests', 'server_latency')
    op.drop_column('tests', 'ping_ms')
    op.drop_column('tests', 'longitude')
    op.drop_column('tests', 'latitude')
    op.drop_column('tests', 'ip')
    op.add_column('servers', sa.Column('latency', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('servers', 'distance_km')
    op.drop_column('servers', 'country_code')
    # ### end Alembic commands ###
